### ISSUE TITLE
Segmentation fault

### ISSUE THREAD

**Issue by nemequ** [lzfse/lzfse#1]
On my Fedora 23 (x86_64) box, I get a segfault when using the lzfse CLI to compress asyoulik.txt from the [Canterbury Corpus](http://corpus.canterbury.ac.nz/descriptions/#cantrbry).  After adding AddressSanitizer to get details (i.e., the segfault happens without it), I get:

```
$ make CFLAGS="-g -fsanitize=address -fno-omit-frame-pointer" && ./build/bin/lzfse -encode -i ~/local/src/squash-benchmark/asyoulik.txt -o compressed.lzfse
cc -g -fsanitize=address -fno-omit-frame-pointer -c src/lzfse_encode.c -o build/obj/lzfse_encode.o
cc -g -fsanitize=address -fno-omit-frame-pointer -c src/lzfse_decode.c -o build/obj/lzfse_decode.o
cc -g -fsanitize=address -fno-omit-frame-pointer -c src/lzfse_encode_base.c -o build/obj/lzfse_encode_base.o
cc -g -fsanitize=address -fno-omit-frame-pointer -c src/lzfse_decode_base.c -o build/obj/lzfse_decode_base.o
cc -g -fsanitize=address -fno-omit-frame-pointer -c src/lzvn_encode_base.c -o build/obj/lzvn_encode_base.o
cc -g -fsanitize=address -fno-omit-frame-pointer -c src/lzvn_decode_base.c -o build/obj/lzvn_decode_base.o
cc -g -fsanitize=address -fno-omit-frame-pointer -c src/lzfse_fse.c -o build/obj/lzfse_fse.o
ld -r -o ./build/obj/liblzfse_master.o ./build/obj/lzfse_encode.o  ./build/obj/lzfse_decode.o ./build/obj/lzfse_encode_base.o ./build/obj/lzfse_decode_base.o ./build/obj/lzvn_encode_base.o ./build/obj/lzvn_decode_base.o ./build/obj/lzfse_fse.o
ar rvs build/bin/liblzfse.a ./build/obj/liblzfse_master.o
ar: creating build/bin/liblzfse.a
a - ./build/obj/liblzfse_master.o
cc -g -fsanitize=address -fno-omit-frame-pointer -c src/lzfse_main.c -o build/obj/lzfse_main.o
cc -g -fsanitize=address -fno-omit-frame-pointer -o build/bin/lzfse ./build/obj/lzfse_main.o ./build/bin/liblzfse.a
=================================================================
==19712==ERROR: AddressSanitizer: unknown-crash on address 0x7fa27100b9ef at pc 0x00000040ac7d bp 0x7ffdbdf24760 sp 0x7ffdbdf24750
READ of size 8 at 0x7fa27100b9ef thread T0
    #0 0x40ac7c in load8 src/lzfse_internal.h:395
    #1 0x40ac7c in lzfse_encode_base src/lzfse_encode_base.c:707
    #2 0x402a83 in lzfse_encode_buffer src/lzfse_encode.c:91
    #3 0x401fb1 in main src/lzfse_main.c:221
    #4 0x7fa26fb01730 in __libc_start_main (/lib64/libc.so.6+0x20730)
    #5 0x4013c8 in _start (/home/nemequ/local/src/lzfse/build/bin/lzfse+0x4013c8)

0x7fa27100b9f6 is located 0 bytes to the right of 250358-byte region [0x7fa270fce800,0x7fa27100b9f6)
allocated by thread T0 here:
    #0 0x7fa26ff6b150 in realloc (/lib64/libasan.so.3+0xc7150)
    #1 0x4014b8 in lzfse_reallocf src/lzfse_main.c:34
    #2 0x401d70 in main src/lzfse_main.c:172
    #3 0x7fa26fb01730 in __libc_start_main (/lib64/libc.so.6+0x20730)

SUMMARY: AddressSanitizer: unknown-crash src/lzfse_internal.h:395 in load8
Shadow bytes around the buggy address:
  0x0ff4ce1f96e0: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  0x0ff4ce1f96f0: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  0x0ff4ce1f9700: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  0x0ff4ce1f9710: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  0x0ff4ce1f9720: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
=>0x0ff4ce1f9730: 00 00 00 00 00 00 00 00 00 00 00 00 00[00]06 fa
  0x0ff4ce1f9740: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
  0x0ff4ce1f9750: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
  0x0ff4ce1f9760: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
  0x0ff4ce1f9770: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
  0x0ff4ce1f9780: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
Shadow byte legend (one shadow byte represents 8 application bytes):
  Addressable:           00
  Partially addressable: 01 02 03 04 05 06 07 
  Heap left redzone:       fa
  Heap right redzone:      fb
  Freed heap region:       fd
  Stack left redzone:      f1
  Stack mid redzone:       f2
  Stack right redzone:     f3
  Stack partial redzone:   f4
  Stack after return:      f5
  Stack use after scope:   f8
  Global redzone:          f9
  Global init order:       f6
  Poisoned by user:        f7
  Container overflow:      fc
  Array cookie:            ac
  Intra object redzone:    bb
  ASan internal:           fe
  Left alloca redzone:     ca
  Right alloca redzone:    cb
==19712==ABORTING
```

**Comment by ebainville** [comment]
Encoder was likely to fail for input size between 32767 and 262144. Fixed.
